"""translation of songs

Revision ID: 15a568e7ece2
Revises: aa7decf64af7
Create Date: 2023-05-26 10:02:12.221660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a568e7ece2'
down_revision = 'aa7decf64af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation',
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('translated_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['translated_id'], ['song.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation')
    # ### end Alembic commands ###
