"""add order in items list

Revision ID: 244809f8d970
Revises: 4ddb08c3a9e1
Create Date: 2023-05-19 23:04:09.116341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244809f8d970'
down_revision = '4ddb08c3a9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.drop_column('item_order')

    # ### end Alembic commands ###
