"""sermon to song removed

Revision ID: 4ddb08c3a9e1
Revises: 6ff9ecbe8c2f
Create Date: 2023-05-19 18:55:50.098805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ddb08c3a9e1'
down_revision = '6ff9ecbe8c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songlist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songlist',
    sa.Column('sermon_id', sa.INTEGER(), nullable=True),
    sa.Column('song_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermon.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    # ### end Alembic commands ###
