"""planner adjustment

Revision ID: 594f70280ff7
Revises: 9352aad4ce2f
Create Date: 2023-06-02 07:42:31.464625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594f70280ff7'
down_revision = '9352aad4ce2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listorder', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('listorder')

    # ### end Alembic commands ###
