"""new start

Revision ID: a1d112b2fcce
Revises: 
Create Date: 2023-06-09 13:02:00.311165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d112b2fcce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('desired_key', sa.Integer(), nullable=True),
    sa.Column('listorder', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listitem_created'), ['created'], unique=False)

    op.create_table('mlinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('mtype', sa.Integer(), nullable=True),
    sa.Column('murl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mlinks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mlinks_filename'), ['filename'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['listitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('RolesTable',
    sa.Column('listitem_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listitem_id'], ['listitem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('Songcart',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('listitem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listitem_id'], ['listitem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mlink', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('list_title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lists_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_lists_date_time'), ['date_time'], unique=False)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('singer', sa.String(length=140), nullable=True),
    sa.Column('info', sa.String(length=140), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('language', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_singer'), ['singer'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_title'), ['title'], unique=False)

    op.create_table('Eventitems',
    sa.Column('lists_id', sa.Integer(), nullable=True),
    sa.Column('listitem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listitem_id'], ['listitem.id'], ),
    sa.ForeignKeyConstraint(['lists_id'], ['lists.id'], )
    )
    op.create_table('list_user',
    sa.Column('lists_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lists_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('medialinks',
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('mlink_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mlink_id'], ['mlinks.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    op.create_table('songlistitem',
    sa.Column('listitem_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listitem_id'], ['listitem.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    op.create_table('songtags',
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('translation',
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('translated_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['translated_id'], ['song.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation')
    op.drop_table('songtags')
    op.drop_table('songlistitem')
    op.drop_table('medialinks')
    op.drop_table('list_user')
    op.drop_table('Eventitems')
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_title'))
        batch_op.drop_index(batch_op.f('ix_song_timestamp'))
        batch_op.drop_index(batch_op.f('ix_song_singer'))

    op.drop_table('song')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))

    op.drop_table('post')
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lists_date_time'))
        batch_op.drop_index(batch_op.f('ix_lists_created'))

    op.drop_table('lists')
    op.drop_table('followers')
    op.drop_table('Songcart')
    op.drop_table('RolesTable')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('tag')
    with op.batch_alter_table('mlinks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mlinks_filename'))

    op.drop_table('mlinks')
    with op.batch_alter_table('listitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listitem_created'))

    op.drop_table('listitem')
    # ### end Alembic commands ###
