"""minor changes

Revision ID: bbb46ce28f91
Revises: ad8084d24987
Create Date: 2023-06-02 13:19:18.270102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb46ce28f91'
down_revision = 'ad8084d24987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar')
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_column('date_end')

    op.create_table('calendar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
